spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
            - key: application.yml
              path: application.yml
      containers:
      - volumeMounts:
          - name: config
            mountPath: /app/config
