CREATE database moses_user DEFAULT CHARSET=utf8;
USE moses_user;
CREATE TABLE `user` (
  `id` bigint(20) NOT NULL COMMENT '用户id',
  `app_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'appid',
  `username` varchar(32) NOT NULL COMMENT '用户名, 缺省为电话号码',
  `password` varchar(128) NOT NULL COMMENT '用户密码',
  `salt` varchar(6) NOT NULL COMMENT '随机字符串',
  `nickname` varchar(32) DEFAULT NULL COMMENT '昵称',
  `email` varchar(128) DEFAULT NULL COMMENT 'email',
  `certificates_type` int(11) DEFAULT '0' COMMENT '证件类型0、身份证，1、护照',
  `certificates_number` varchar(18) DEFAULT NULL COMMENT '证件号',
  `phone_number` varchar(32) DEFAULT NULL COMMENT '手机',
  `gender` int(11) DEFAULT '0' COMMENT '性别（0、女，1、男）',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像：图片服务链接',
  `identity_card_front` varchar(255) DEFAULT NULL COMMENT '身份证正面照片',
  `identity_card_back` varchar(255) DEFAULT NULL COMMENT '身份证反面照片',
  `is_certificated` int(11) DEFAULT '0' COMMENT '是否实名认证（0、否，1、是）',
  `register_date` bigint(20) DEFAULT '0' COMMENT '注册时间',
  `update_date` bigint(20) DEFAULT '0' COMMENT '修改时间',
  `status` int(11) DEFAULT '0' COMMENT '状态（0、正常，1、禁用）',
  `qq_uid` varchar(64) DEFAULT NULL COMMENT 'qq登录提供者UID',
  `qq_bound_time` bigint(20) DEFAULT '0' COMMENT 'qq平台绑定时间',
  `qq_unbound_time` bigint(20) DEFAULT '0' COMMENT 'qq平台解绑时间',
  `qq_bind_status` int(11) DEFAULT '0' COMMENT 'qq平台是否绑定0、解绑，1、绑定',
  `wechat_uid` varchar(64) DEFAULT NULL COMMENT 'wechat登录提供者UID',
  `wechat_bound_time` bigint(20) DEFAULT '0' COMMENT 'wechat平台绑定时间',
  `wechat_unbound_time` bigint(20) DEFAULT '0' COMMENT 'wechat平台解绑时间',
  `wechat_bind_status` int(11) DEFAULT '0' COMMENT 'wechat平台是否绑定0、解绑，1、绑定',
  `weibo_uid` varchar(64) DEFAULT NULL COMMENT 'weibo登录提供者UID',
  `weibo_bound_time` bigint(20) DEFAULT '0' COMMENT 'weibo平台绑定时间',
  `weibo_unbound_time` bigint(20) DEFAULT '0' COMMENT 'weibo平台解绑时间',
  `weibo_bind_status` int(11) DEFAULT '0' COMMENT 'weibo平台是否绑定0、解绑，1、绑定',
  `reserved_str_01` varchar(128) DEFAULT NULL COMMENT '备用字段01',
  `reserved_str_02` varchar(128) DEFAULT NULL COMMENT '备用字段02',
  `reserved_str_03` varchar(128) DEFAULT NULL COMMENT '备用字段03',
  `reserved_str_04` varchar(128) DEFAULT NULL COMMENT '备用字段04',
  `reserved_str_05` varchar(128) DEFAULT NULL COMMENT '备用字段05',
  `reserved_str_06` varchar(128) DEFAULT NULL COMMENT '备用字段06',
  `reserved_str_07` varchar(128) DEFAULT NULL COMMENT '备用字段07',
  `reserved_str_08` varchar(128) DEFAULT NULL COMMENT '备用字段08',
  `reserved_str_09` varchar(128) DEFAULT NULL COMMENT '备用字段09',
  `reserved_str_10` varchar(128) DEFAULT NULL COMMENT '备用字段10',
  `reserved_int_11` int(11) DEFAULT '0' COMMENT '备用字段11',
  `reserved_int_12` int(11) DEFAULT '0' COMMENT '备用字段12',
  `reserved_int_13` int(11) DEFAULT '0' COMMENT '备用字段13',
  `reserved_int_14` int(11) DEFAULT '0' COMMENT '备用字段14',
  `reserved_int_15` int(11) DEFAULT '0' COMMENT '备用字段15',
  `reserved_int_16` int(11) DEFAULT '0' COMMENT '备用字段16',
  `reserved_int_17` int(11) DEFAULT '0' COMMENT '备用字段17',
  `reserved_int_18` int(11) DEFAULT '0' COMMENT '备用字段18',
  `reserved_int_19` int(11) DEFAULT '0' COMMENT '备用字段19',
  `reserved_int_20` int(11) DEFAULT '0' COMMENT '备用字段10',
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_number_unique` (`phone_number`),
  KEY `qq_uid_index` (`qq_uid`),
  KEY `wechat_uid_index` (`wechat_uid`),
  KEY `weibo_uid_index` (`weibo_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表,用户表为100张，名字分为user_001~user_100'
#create user
CREATE user kfman@'localhost' IDENTIFIED BY 'Kfman123!';
#grant user
grant all privileges on moses_user.* to kfman@'%' identified by 'Kfman123!' ;
